### PR TITLE
Changes made to support node-krb5 on z/OS

### PR DESCRIPTION
**Pull request by alexcfyung**
This PR contains changes made to support node-krb5 on z/OS, it included modification in src and change installation process.

### CODE REVIEW

**Comment by wdavidw** [comment]
Thank you for the contribution. A few notes:
* Why do you introduce the "MANUAL" env variable
* We could have only one *install.sh` script, the plaform could be obtained with `node -e 'process.stdout.write(os.platform())'` inside of it

**Comment by alexcfyung** [comment]
> Why do you introduce the "MANUAL" env variable

Currently the default behavior of running `npm install` is executing `node install.js`, if the platform is z/OS, it will always run `install_krb5_zos.sh`, so I want to provide a way for the user to flexibly install krb5 themselves and `npm install` without running `install_krb5_zos.sh`

> We could have only one *install.shscript, the plaform could be obtained withnode -e 'process.stdout.write(os.platform())'` inside of it

I am not sure what do you mean, I added `install.sh` before as the command to execute for `npm install`, but later realise it doesn't support windows so I changed it to `install.js` and execute `node install.js` instead, currently the branch have `install.js`, `install_krb5_zos.sh` and `install_krb5.sh` and doesn't have any `install.sh`.

I check the failure in travis it seems to occur because `docker-compose.yml` doesn't include `install.js` nor `install_krb5_zos.sh` in the container.

**Comment by wdavidw** [comment]
OK, your points are valid. However, we choose to not download the source or binary of Kerberos and instead document the procedure for each plateform and let the user do it. I am not saying it is a good thing nor a bad thing but I believe the behavior shall be the same for every plateform, wether we do one strategory or both based on the presence of an environmental variable like `MANUAL`. @alexcfyung @RReivax what are your opinions ?

**Comment by alexcfyung** [comment]
I see what you mean. I can share why I choose to download the binary for krb5 just for z/OS. It is because z/OS is a special case and different than other platform, in other platform krb5 are widely supported and available, but in z/OS I need to build the libraries and ship them, this is the location of the repo: https://github.com/ibmruntimes/libkrb5-zos. It is only meant to used with this npm, because of this special situation, I choose to download the binaries as well to save user some trouble.

**Comment by wdavidw** [comment]
I kind of faced the same concerned a few years back with the first version of this package on OSX (probably still the case). Here's what I propose:
1. we document the process of installing a package or downloading/compiling the source code or binary for each plateform, whatever is the easiest.
2. we provide a script which does the kerberos installation for each platforme but which is only activated with options like `KRB5_SOURCE` and `KRB5_BINARY`. Note, we could add a `KRB5_CHECKSUM` to validate the download.

**Comment by alexcfyung** [comment]
For number 2, I think it make sense to unique platform like z/OS, because it is rather difficult for user to install krb5 themselves and they most likely going to use the krb5 I provided, but for other well supported platform such as linux, user may have their preferred way to install krb5.

**Comment by alexcfyung** [comment]
Do we have a conclusion on the way to go for?

**Comment by alexcfyung** [comment]
I reverted back the install changes and add some instruction for zos in README, please review the changes.

**Comment by wdavidw** [comment]
This works for me. Thank you

**Comment by wdavidw** [comment]
Quick note, version 0.5.3 was released last week with the changes

**Pull request merged**
