### PR TITLE
Add github actions as CI

### PR DESCRIPTION
**Pull request by Guillaume-Boutry**
This is a sample CI, executing docker tests on all 3 target OS (archlinux, centos7, Ubuntu).

If want to use this also as a CD, we could add the following:

In the event section:
```
on:
  release:
    types:
      - created
```

And then add a job with the condition:
```
if: github.event_name == 'release' && github.event.action == 'created'
```

### CODE REVIEW

**Comment by Guillaume-Boutry** [comment]
I forked the project, and ran the CI with the same configuration and it worked.

Seems to have problems with Centos7 repository.

I have a colleague who had similar issues this morning on a centos7 Box in vagrant

**Comment by wdavidw** [comment]
Thanks, we don't need CD for now. Yes, invalid checksum for https://repo.ius.io/7/x86_64/repodata/primary.xml.gz

**Comment by Guillaume-Boutry** [comment]
The disfonctionning image was the image "rest" it failed again for Archlinux, but was built successfully for centos7 and ubuntu. 

We might need to wait a bit to give them time to stabilize. (Might be a release on-going)

**Comment by Guillaume-Boutry** [comment]
https://repo.ius.io/7/x86_64/repodata/primary.xml.gz this file was released at `09/13/2021, 02:50:36 PM`, looks like some cache issue due to new release.

**Comment by Guillaume-Boutry** [comment]
I removed the installation from community repository, to let yum install get components from the official repositories.

The python version installed is the same: `3.6.8-18.el7`

**Pull request merged**
